using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace PlaceYourBets.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaceYourBets.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap ARS {
			get {
				object obj = ResourceManager.GetObject("ARS", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap AST {
			get {
				object obj = ResourceManager.GetObject("AST", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap BUR {
			get {
				object obj = ResourceManager.GetObject("BUR", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap CHE {
			get {
				object obj = ResourceManager.GetObject("CHE", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap CRY {
			get {
				object obj = ResourceManager.GetObject("CRY", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap EVE {
			get {
				object obj = ResourceManager.GetObject("EVE", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap HUL {
			get {
				object obj = ResourceManager.GetObject("HUL", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap icon2 {
			get {
				object obj = ResourceManager.GetObject("icon2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap LEI {
			get {
				object obj = ResourceManager.GetObject("LEI", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap LIV {
			get {
				object obj = ResourceManager.GetObject("LIV", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap MNC {
			get {
				object obj = ResourceManager.GetObject("MNC", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap MNU {
			get {
				object obj = ResourceManager.GetObject("MNU", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap NWC {
			get {
				object obj = ResourceManager.GetObject("NWC", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap pitch {
			get {
				object obj = ResourceManager.GetObject("pitch", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap pitch1 {
			get {
				object obj = ResourceManager.GetObject("pitch1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap QPR {
			get {
				object obj = ResourceManager.GetObject("QPR", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SOU {
			get {
				object obj = ResourceManager.GetObject("SOU", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap STO {
			get {
				object obj = ResourceManager.GetObject("STO", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SUN {
			get {
				object obj = ResourceManager.GetObject("SUN", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SWA {
			get {
				object obj = ResourceManager.GetObject("SWA", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap title {
			get {
				object obj = ResourceManager.GetObject("title", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap TOT {
			get {
				object obj = ResourceManager.GetObject("TOT", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap WBA {
			get {
				object obj = ResourceManager.GetObject("WBA", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap WHU {
			get {
				object obj = ResourceManager.GetObject("WHU", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
